"""
models/schemas.py
-----------------
Central data definitions for the Agentic Research Planning Framework.
All dataclasses used across agents and tools are defined here.
No logic. No external dependencies.
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Paper:
    """
    Represents a single research paper retrieved from arXiv.

    Attributes:
        title       : Full paper title.
        abstract    : Full abstract text.
        arxiv_id    : arXiv entry URL (e.g. 'http://arxiv.org/abs/2301.00001v1').
        concepts    : Key technical concepts extracted by the Librarian Agent.
                      Empty list on retrieval — populated after LLM extraction.
    """
    title: str
    abstract: str
    arxiv_id: str
    concepts: List[str] = field(default_factory=list)


@dataclass
class ResearchGap:
    """
    Represents a weakly explored research area identified by the Librarian Agent.

    Attributes:
        description          : Human-readable description of the gap.
        related_concepts     : Concepts that surround or define the gap.
        supporting_paper_ids : arXiv IDs of papers that reveal the gap.
    """
    description: str
    related_concepts: List[str]
    supporting_paper_ids: List[str]


@dataclass
class ResearchPlan:
    """
    A single candidate research plan generated by the Planner Agent.

    Attributes:
        research_question : The core question the plan seeks to answer.
        proposed_method   : High-level approach or technique to be used.
        dataset           : Name of the dataset proposed for evaluation.
        evaluation_metric : Metric used to measure success.
        source_gap        : The ResearchGap this plan was generated from.
                            Required for the revision loop in main.py.
    """
    research_question: str
    proposed_method: str
    dataset: str
    evaluation_metric: str
    source_gap: Optional[ResearchGap] = None


@dataclass
class ReviewResult:
    """
    The output of the Reviewer Agent for a single ResearchPlan.

    Attributes:
        plan                  : The ResearchPlan that was evaluated.
        novelty_score         : Float 0.0–10.0. Higher = more novel vs existing literature.
        feasibility_passed    : True if dataset and metric pass rule-based checks.
        feasibility_notes     : Human-readable explanation of feasibility result.
        suggested_title       : LLM-generated title for the research proposal.
        research_direction    : Concise description of the research opportunity.
        experimental_blueprint: High-level plan for how the idea could be tested.
        accepted              : True only if novelty_score >= threshold AND feasibility passes.
    """
    plan: ResearchPlan
    novelty_score: float
    feasibility_passed: bool
    feasibility_notes: str
    suggested_title: str
    research_direction: str
    experimental_blueprint: str
    accepted: bool
